[project]
name = "llmge-x-alphaevolve"
version = "0.1.0"
description = "LLM Guided Evolution for Circuit Design"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deap==1.4.1",
    "flake8>=7.2.0",
    "furo>=2024.8.6",
    "numpy>=2.0.2",
    "pyyaml",
    "requests",
    "huggingface_hub",
    "google-genai>=1.12.1",
    "pytest>=8.3.5",
    "sphinx>=8.2.3",
    "torch==2.6.0",
    "torchvision",
    "transformers",
    "accelerate",
    "fastapi",
    "uvicorn",
    "pydantic",
    "tqdm",
    "hydra-core==1.3.2",
    "omegaconf",
    "kaggle>=1.7.4.5",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.2",
    "imblearn",
    "jax>=0.9.0.1",
    "optax>=0.2.7",
]
